### ISSUE TITLE
Could not open socket - INT_RSA_VERIFY - Intel Celeron N3450 -

### ISSUE THREAD

**Issue by AndryBray** [emailjs/emailjs-imap-client#178]
I'm getting this error with a new PC with Windows 10 Home (v 1709 build 16299.248) / nwjs app

Intel Celeron N3450 - 1.10Ghz - 8Gb Ram - x64

```

"Could not connect to server"

"Error: Could not open socket: 101057795:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:e:\build\nw19_sdk_win64\node-webkit\src\third_party\node\deps\openssl\openssl\crypto\rsa\rsa_sign.c:278:
101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:e:\build\nw19_sdk_win64\node-webkit\src\third_party\node\deps\openssl\openssl\ssl\s3_clnt.c:2010:

    at socket.onerror (C:\Users\Admin\AppData\Local\Temp\nw3924_15942\node_modules\emailjs-imap-client\src\emailjs-imap-client-imap.js:135:24)
    at TCPSocket._emit (C:\Users\Admin\AppData\Local\Temp\nw3924_15942\node_modules\emailjs-imap-client\node_modules\emailjs-tcp-socket\src\emailjs-tcp-socket.js:1088:9)
    at TLSSocket.<anonymous> (C:\Users\Admin\AppData\Local\Temp\nw3924_15942\node_modules\emailjs-imap-client\node_modules\emailjs-tcp-socket\src\emailjs-tcp-socket.js:324:26)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)"
```

Any idea if it's something related to emailjs lib or nodejs?

PS: the same app/script works well on other Windows 10 PC and MacOS

**Comment by AndryBray** [comment]
I see it's something related to Nodejs and Intel Celeron... Upgrading to last nwjs/nodejs it works.
Do you know any workaround for this https://github.com/nodejs/node/issues/12691?

**Comment by felixhammerl** [comment]
This is an SSL issue that's either in the node internals, your machine architecture, or your openssl version (unless you're using the websocket shim, which apparently you're not). Sorry about that, but I'm pretty sure that's out of scope :(

p.s. You're using an outdated version of the library ;)
