### ISSUE TITLE
Error: Delete Mail -> Command received in invalid state

### ISSUE THREAD

**Issue by NetHans** [emailjs/emailjs-imap-client#205]
if I want to delete an email, I always get following error message
Server: Microsoft Exchange Server 2016

`[DEBUG][2019-03-07T14:53:25.282Z][1][---][....] C: W11 UID FETCH 1 (UID BODY[])
[DEBUG][2019-03-07T14:53:25.314Z][1][---][....] S: * 1 FETCH (UID 1 BODY[] "(* 40975B literal *)")
[DEBUG][2019-03-07T14:53:25.314Z][1][---][....] S: W11 OK FETCH completed.
[DEBUG][2019-03-07T14:53:25.361Z][1][---][....] Deleting messages 1 in Test000 ...
[DEBUG][2019-03-07T14:53:25.361Z][1][---][....] Setting flags on 1 in Test000 ...
[DEBUG][2019-03-07T14:53:25.361Z][1][---][....] C: W12 STORE 1 +FLAGS (\Deleted)
[DEBUG][2019-03-07T14:53:25.361Z][1][---][....] S: W12 NO Command received in Invalid state.
Error: Command received in Invalid state.
    at Object.callback (.\node_modules\emailjs-imap-client\dist\imap.js:289:25)
    at Imap._handleResponse (.\node_modules\emailjs-imap-client\dist\imap.js:621:28)
    at Imap._parseIncomingCommands (.\node_modules\emailjs-imap-client\dist\imap.js:585:12)
    at Imap._onData (.\node_modules\emailjs-imap-client\dist\imap.js:428:10)
    at TCPSocket.socket.ondata.evt [as ondata] (.\node_modules\emailjs-imap-client\dist\imap.js:160:16)
    at TCPSocket._emit (.\node_modules\emailjs-tcp-socket\dist\node-socket.js:103:31)
    at TLSSocket.<anonymous> (.\node_modules\emailjs-tcp-socket\dist\node-socket.js:69:23)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
[DEBUG][2019-03-07T14:53:25.376Z][1][---][....] Entering state: 5
[DEBUG][2019-03-07T14:53:25.376Z][1][---][....] Logging out...
[DEBUG][2019-03-07T14:53:25.376Z][1][---][....] C: W13 LOGOUT
[DEBUG][2019-03-07T14:53:25.376Z][1][---][....] S: * BYE Microsoft Exchange Server 2016 IMAP4 server signing off.
[DEBUG][2019-03-07T14:53:25.376Z][1][---][....] S: W13 OK LOGOUT completed.`

**Comment by NetHans** [comment]
I found my mistake. The mailbox was in readonly mode. 
A clearer error message might be helpful.
