### ISSUE TITLE
SyntaxError: Unexpected token > 

### ISSUE THREAD

**Issue by tojibon** [emailjs/emailjs-imap-client#94]
Is there anyone who can explain me why I am facing this issue:

```javascript

.\node_modules\emailjs-imap-client\src\emailjs-imap-client.js:57
        this.client.oncert = (cert) => (this.oncert && this.oncert(cert)); //
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.\api\policies\imap.js:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at .\node_modules\include-all\index.js:129:29
    at Array.forEach (native)
    at requireAll (.\node_modules\include-all\index.js:44:9)
    at buildDictionary (.\node_modules\sails-build-dictionary\index.js:68:14)
    at Function.module.exports.optional (.\node_modules\sails-build-dictionary\index.js:160:9)

```

I am not sure but I think it causing by below like code syntax:
```javascript
client.logout().then(() => { /* connection terminated */ });
```

But if I use this way its safe:
```javascript
client.logout().then(function(){ /* connection terminated */ });
```

Thanks in advance

**Comment by tojibon** [comment]
_**To be noted: **_

I am using node version: v0.10.24
And Sailsjs: v0.11.2

**Comment by felixhammerl** [comment]
node v0.10 can't parse ES6 w/o `--harmony` runtime flag. either upgrade to a newer node version (why os 0.10 even still around, we're at v6.0.0), or use babel to transpile the code.
